# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: node:fermium-buster-slim
variables:
  GKAPP_URL: https://gnukhata.gitlab.io/gkapp
pages:
  stage: build
  script:
  - npm install
  - npm run build
  - mv public _pub && mv dist public
  - gzip -k -9 $(find public -type f)
  artifacts:
    paths:
    - public
  only:
  - master
  - dev
stages:
- test
- build
sast:
  stage: build
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml
