# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: node:fermium-alpine3.14 #node:fermium-buster-slim
stages:
  - build
  - test
  - deploy
variables:
  GKAPP_URL: https://gnukhata.gitlab.io/gkapp

# build gkapp
gkapp:
  stage: build
  script:
    - npm install -g @vue/cli
    - npm install
    - npm run build-dev
    - echo $NODE_ENV
  artifacts:
    paths:
      - dist
# gzip files & deploy to gitlab pages
pages:
  stage: deploy
  needs:
    - job: gkapp
      artifacts: true
  script:
    - ls -al
    - mv public _pub
    - mv dist public
    - gzip -k -9 $(find public -type f)
  artifacts:
    paths:
      - public
  only:
    - master
    - devel

# SAST Tests
sast:
  stage: test
  variables:
    SAST_EXCLUDED_PATHS: spec, test, tests, tmp, dist, package-lock.json
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
