image: node:fermium-buster-slim
environment:
  GKAPP_URL: 'https://gnukhata.gitlab.io/gkapp'
pages:
  stage: build
  script:
    - npm install
    - npm run build
    - mv public _pub && mv dist public
  artifacts:
    paths:
      - public
  only:
    - master
    - dev
