# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
  - build
  - deploy
  - test

variables:
  DOCKER_TLS_CERTDIR: '/certs'

workflow:
  # run pipeline only on creating merge requests, tags or pushing to default branch
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# build gkapp
build_gkapp:
  stage: build
  image: node:gallium-alpine
  script:
    # install dependencies & build
    - npm install -g @vue/cli && npm install
    # run lint on project files
    - npm run lint src/
    # then build, dist/ has the artifact
    - npm run build
  artifacts:
    paths:
      - dist

services:
  - docker:20.10.19-dind

# build gkapp docker image from devel commits & upload it to docker hub
docker-devel:
  image: docker:20.10.19
  stage: build
  script:
    # build the docker image & push to the dockerhub
    - docker login -u digitalfreedom -p $DOCKERHUB_PWD
    - docker build -t digitalfreedom/gkapp:devel --build-arg VERSION=$CI_COMMIT_SHORT_SHA .
    - docker push digitalfreedom/gkapp:devel
  rules:
    - if: $CI_COMMIT_BRANCH == 'devel'

# build gkapp docker image on a release & push it to the docker hub
docker-prod:
  image: docker:20.10.19
  stage: build
  script:
    # build the docker image & push to the dockerhub
    - docker login -u digitalfreedom -p $DOCKERHUB_PWD
    - docker build -t digitalfreedom/gkapp:$CI_COMMIT_TAG --build-arg VERSION=$CI_COMMIT_TAG .
    - docker push digitalfreedom/gkapp:$CI_COMMIT_TAG
    # create alias for the latest tag
    - docker tag digitalfreedom/gkapp:$CI_COMMIT_TAG digitalfreedom/gkapp:latest
    - docker push digitalfreedom/gkapp:latest
  rules:
    - if: $CI_COMMIT_TAG

# SAST Tests
sast:
  stage: test
  variables:
    SAST_EXCLUDED_PATHS: spec, test, tests, tmp, dist, package-lock.json
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

# runs the ui tests against the dev server
ui_tests:
  image: digitalfreedom/nexial-core:latest
  stage: test
  # this job runs with a delay to make sure the dev server
  # is updated to latest commit
  script: |
    cd tests/artifact
    nexial.sh -plan plan/GNUKhata-plan.xlsx || true
    cd -
  # this job runs only on the master branch
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: delayed
      start_in: 2 minutes

  artifacts:
    paths:
      - tests/output/

# deploy devel branch changes to gkcore test server
update_test_server:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - curl -f $TEST_SERVER_HOOK
  rules:
    - if: $CI_COMMIT_BRANCH == 'devel'
