image: node:fermium-buster-slim

variables:
  GKAPP_URL: 'https://gnukhata.gitlab.io/gkapp'

pages:
  stage: build
  script:
    - npm install
    - npm run build
    - mv public _pub && mv dist public
    - gzip -k -9 $(find public -type f)
  artifacts:
    paths:
      - public
  only:
    - master
    - dev
